# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browsers',
            fields=[
                ('browser_type', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
