# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0002_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='namae',
            new_name='name',
        ),
    ]
